---
title: 'Project3: Cartography'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

#Part1: Dollars spent by different countries on HIV or all diseases

```{r message=FALSE, warning=FALSE}

library(readr)
library(tidyverse)
library(dplyr)
library(OpenStreetMap)
library(mapview)
library(mapedit)
library(sf)
library(tidyverse)
library(janitor)
library(ggrepel)


world <- st_read("data/ne_110m_admin_0_countries.shp") %>% 
  clean_names()

sf::sf_use_s2(FALSE)

spending_2019 <- read_csv("Data/IHME_DAH_DATABASE_1990_2019_Y2020M04D23.CSV") %>%
  filter(year == 2019)


spending_source <- spending_2019 %>%
  select(
    source, contains(c("hiv", "mal", "tb", "ncd"))
  ) 

  # mutate(name_sort = case_when(name_sort == "Macedonia, FYR" ~ "North Macedonia",
  #        name_sort=="Slovak Republic" ~ "Slovakia",
  #        TRUE ~ as.character(name_sort)))

spending_long_hiv <- spending_source%>%
  pivot_longer(cols = contains(c("hiv", "mal", "tb", "ncd"))) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(disease = str_extract(name, "[^_]+")) %>%
  select(-name) %>% 
  filter(disease=="hiv") %>% 
  group_by(source) %>% 
  summarize(expenditure_hiv = sum(value, na.rm = TRUE)) %>% 
  mutate(source=str_replace_all(source,"_"," ")) %>% 
  mutate(expenditure_hiv_millions=expenditure_hiv/1e6)

spending_long_alldiseases <- spending_source%>%
  pivot_longer(cols = contains(c("hiv", "mal", "tb", "ncd"))) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(disease = str_extract(name, "[^_]+")) %>%
  select(-name) %>% 
  group_by(source) %>% 
  summarize(expenditure_alldiseases = sum(value, na.rm = TRUE))%>% 
  mutate(source=str_replace_all(source,"_"," "))%>% 
  mutate(expenditure_alldiseases_millions=expenditure_alldiseases/1e6)

data_Q1_hiv <-world  %>%
  left_join(spending_long_hiv, c("name_long"="source")) %>%
  rename(source=name) 

data_Q1_alldiseases <-world  %>%
  left_join(spending_long_alldiseases, c("name_long"="source")) %>% 
 rename(source=name) 

#  sort_A3,recipientISO code

ggplot() + 
coord_sf()+ 
  geom_sf(data = data_Q1_hiv,
                    aes(fill = expenditure_hiv_millions))+theme_void()+
  labs(title="Expenditure in treating HIV disease by different countries for year 2019",
       caption = "Source: IHME Development Assistance for Health Database") +
  scale_fill_continuous(name =  "Expenditure in millions (USD)")

ggplot() + 
coord_sf()+ 
  geom_sf(data = data_Q1_alldiseases,
                    aes(fill = expenditure_alldiseases_millions))+theme_void()+
  labs(title="Expenditure in treating all diseases by different countries for year 2019",
       caption = "Source: IHME Development Assistance for Health Database")+
  scale_fill_continuous(name =  "Expenditure in millions (USD)")
  
```

#Part2: Dollars received by countries

```{r}
  
spending_2015 <- read_csv("Data/IHME_DAH_DATABASE_1990_2019_Y2020M04D23.CSV") %>%
  filter(year == 2015)


spending_recipient <- spending_2015 %>%
  select(
    recipient_isocode, contains(c("hiv", "mal", "tb", "ncd"))
  )

spending_long_alldiseases_recipient <- spending_recipient%>%
  pivot_longer(cols = contains(c("hiv", "mal", "tb", "ncd"))) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(disease = str_extract(name, "[^_]+")) %>%
  select(-name) %>% 
  group_by(recipient_isocode) %>% 
  summarize(expenditure_alldiseases = sum(value, na.rm = TRUE))%>% 
  mutate(expenditure_alldiseases_millions=expenditure_alldiseases/1e6)

data_Q2_alldiseases <-world  %>%
  left_join(spending_long_alldiseases_recipient, c("iso_a3"="recipient_isocode")) %>% 
  rename(recipient=iso_a3)
  

ggplot() + 
coord_sf()+ 
  geom_sf(data = data_Q2_alldiseases,
                    aes(fill = expenditure_alldiseases_millions))+theme_void()+
  labs(title="Money received by for treating all diseases in 2015",
       caption = "Source: IHME Development Assistance for Health Database") +
  scale_fill_continuous(name =  "Money received in millions (USD)")
  
```

#Part3: Map by gbd region

```{r}

library(rworldmap)

dQ3<-data_Q1_alldiseases %>% 
  group_by(region_wb) %>% 
  summarise(expenditure_alldiseases_millions=sum(expenditure_alldiseases_millions,
                                                 na.rm=T))


ggplot() + 
coord_sf()+ 
  geom_sf(data = dQ3,
                    aes(fill = expenditure_alldiseases_millions))+theme_void()+
  labs(title="Dollars received by Europe continent in treating all diseases for year 2015",
       caption = "Source: IHME Development Assistance for Health Database") 

# # gbd_shapefile<- 
# #   mapByRegion(inFile=world, regionType = "GBD", joinCode = "ISO3")
# # 
# # # gbd_shapefile<- st_read("data/SHAPEFILE/admin_1.shp") %>% # could not find it..
# # #   clean_names()
# 
# sf::sf_use_s2(FALSE)
# 
# spending_2018 <- read_csv("Data/IHME_DAH_DATABASE_1990_2019_Y2020M04D23.CSV") %>%
#   filter(year == 2016)
# 
# 
# spending_recipient <- spending_2018 %>%
#   select(
#     recipient_isocode, contains(c("hiv", "mal", "tb", "ncd"))
#   )
# 
# spending_long_alldiseases_recipient <- spending_recipient%>%
#   pivot_longer(cols = contains(c("hiv", "mal", "tb", "ncd"))) %>%
#   mutate(value = as.numeric(value)) %>% 
#   mutate(disease = str_extract(name, "[^_]+")) %>%
#   select(-name) %>% 
#   group_by(recipient_isocode) %>% 
#   summarize(expenditure_alldiseases = sum(value, na.rm = TRUE))%>% 
#   mutate(expenditure_alldiseases_millions=expenditure_alldiseases/1e6)
# 
# 
# data_Q3_alldiseases <-dF  %>%
#   left_join(spending_long_alldiseases_recipient, c("name"="gbd")) 
```

#Part4: Spending by recipient country across time

```{r}
  
spending_time <- read_csv("Data/IHME_DAH_DATABASE_1990_2019_Y2020M04D23.CSV") 

spending_recipient_time <- spending_time %>%
  select(
    recipient_country, contains(c("hiv", "mal", "tb", "ncd"))
  )

spending_recipient_all_disease_time <- spending_recipient_time%>%
  pivot_longer(cols = contains(c("hiv", "mal", "tb", "ncd"))) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(disease = str_extract(name, "[^_]+")) %>%
  select(-name) %>% 
  group_by(recipient_country) %>% 
  summarize(expenditure_alldiseases = sum(value, na.rm = TRUE))

data_Q4_alldiseases <-world  %>%
  left_join(spending_recipient_all_disease_time, c("name_sort"="recipient_country")) %>% 
  rename(source=name_sort)

# Did not get the point of merging shapefiles by time
  
```

#Part5: Interactive chloropeth map for year 2015

```{r}
       
```

#Part6: Spending by one country: Australia for year 2015

```{r}

europe_cropped <- st_crop(world, xmin = -25, xmax = 50, ymin = 30, ymax = 73)

europe_cropped <- europe_cropped %>% 
  mutate(name_sort = case_when(name_sort == "Macedonia, FYR" ~ "North Macedonia",
         name_sort=="Slovak Republic" ~ "Slovakia",
         TRUE ~ as.character(name_sort)))

data_Q6_Europe <-europe_cropped  %>%
  left_join(spending_long_alldiseases_recipient, c("name_sort"="recipient_country")) %>% 
#  sort_A3,recipientISO code

  rename(source=name_sort)

ggplot() + 
coord_sf()+ 
  geom_sf(data = data_Q6_Europe,
                    aes(fill = expenditure_alldiseases))+theme_void()+
  labs(title="Dollars received by Europe continent in treating all diseases for year 2015",
       caption = "Source: IHME Development Assistance for Health Database") 
       
```


#Part7: Plotting  using SITG shapefiles and 3 different layers

```{r}

library(tmap)
library(sf)
library(raster)

sitg<- st_read("data/sitg/CAD_BATIMENT_HORSOL_TOIT_SP.shp") %>% 
  clean_names()

tm_shape(sitg)+
  tm_polygons()
```

#Part8: City plot using OpenStreetMap

```{r}
library(rworldmap)
library(osmdata)
data(countryRegions,envir=environment(),package="rworldmap")

# gbdregions <- countryRegions %>%
#   select(ISO3, ADMIN, GBD) %>%
#   filter(!is.na(GBD))

getbb("zurich") %>% 
  opq()

getbb("zurich") %>% 
    opq() %>%
  add_osm_feature(
    key = "highway",
    value = c(
      "motorway", "primary",
      "secondary", "tertiary"
    )
  )%>%
  osmdata_sf()

library(purrr)


getbb("zurich") %>%
  opq() %>%
  add_osm_feature(
    key = "highway",
    value = c(
      "motorway", "primary",
      "secondary", "tertiary"
    )
  ) %>%
  osmdata_sf() %>%
  purrr::pluck("osm_lines") %>%
  glimpse()

getbb("zurich") %>%
  opq() %>%
  add_osm_feature(
    key = "highway",
    value = c(
      "motorway", "primary",
      "secondary", "tertiary"
    )
  ) %>%
  osmdata_sf() %>%
  purrr::pluck("osm_lines") %>%
  ggplot() +
  geom_sf(aes(color = highway))

opq(c(8.448006, 47.320220,  8.625441,  47.434666)) %>%
  add_osm_feature(
    key = "highway",
    value = c(
      "motorway", "primary",
      "secondary", "tertiary"
    )
  ) %>%
  osmdata_sf() %>%
  purrr::pluck("osm_lines") %>%
  ggplot() +
  geom_sf(aes(color = highway)) +
  theme_void()

```
