---
title: 'Project4: Volcano Eruption Visualization'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

#Part1: Getting the data

```{r}

library(readr)
library(tidyverse)
library(dplyr)
library(readtext)
library(tidygraph)
library(ggplot2)
library(janitor)
library(OpenStreetMap)
library(mapview)
library(mapedit)
library(sf)
library(forcats)
library(kableExtra)
library(ggpomological)
library(RColorBrewer)

volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
tree_rings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')
```

#Part1: Circular bar chart 

```{r}

data<-volcano %>% 
  select(volcano_name, last_eruption_year,contains("population")) %>% 
mutate(last_eruption_year = na_if(last_eruption_year, "Unknown")) %>% 
  drop_na

# # Set a number of 'empty bar' to add at the end of each group
# empty_bar <- 3
# to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$group), ncol(data)) )
# colnames(to_add) <- colnames(data)
# to_add$group <- rep(levels(data$group), each=empty_bar)
# data <- rbind(data, to_add)
# data <- data %>% arrange(group)
# data$id <- seq(1, nrow(data))
#  
# # Get the name and the y position of each label
# label_data <- data
# number_of_bar <- nrow(label_data)
# angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
# label_data$hjust <- ifelse( angle < -90, 1, 0)
# label_data$angle <- ifelse(angle < -90, angle+180, angle)
#  
# # prepare a data frame for base lines
# base_data <- data %>% 
#   group_by(group) %>% 
#   summarize(start=min(id), end=max(id) - empty_bar) %>% 
#   rowwise() %>% 
#   mutate(title=mean(c(start, end)))
#  
# # prepare a data frame for grid (scales)
# grid_data <- base_data
# grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
# grid_data$start <- grid_data$start - 1
# grid_data <- grid_data[-1,]
#  
# # Make the plot
# p <- ggplot(data, aes(x=as.factor(id), y=value, fill=group)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
#   
#   geom_bar(aes(x=as.factor(id), y=value, fill=group), stat="identity", alpha=0.5) +
#   
#   # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
#   geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
#   geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
#   geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
#   geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
#   
#   # Add text showing the value of each 100/75/50/25 lines
#   annotate("text", x = rep(max(data$id),4), y = c(20, 40, 60, 80), label = c("20", "40", "60", "80") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
#   
#   geom_bar(aes(x=as.factor(id), y=value, fill=group), stat="identity", alpha=0.5) +
#   ylim(-100,120) +
#   theme_minimal() +
#   theme(
#     legend.position = "none",
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     panel.grid = element_blank(),
#     plot.margin = unit(rep(-1,4), "cm") 
#   ) +
#   coord_polar() + 
#   geom_text(data=label_data, aes(x=id, y=value+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) +
#   
#   # Add base line information
#   geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
#   geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(1,1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)
#  
# p
 
```

#Part2: Initial visualization

```{r}

world <- st_read("data/ne_110m_admin_0_countries.shp") %>% 
  clean_names() %>% 
  #rename(country=sovereignt) %>% 
  mutate(name_sort = case_when(name_sort == "Macedonia, FYR" ~ "North Macedonia",
         name_sort=="Slovak Republic" ~ "Slovakia",
         name_sort=="United States of America" ~ "United States",
         TRUE ~ as.character(name_sort)))

dVolcano <-world  %>%
  left_join(volcano, c("name_sort"="country")) %>% 
  rename(country=name_sort) 

dVolcano<-dVolcano %>% 
  mutate(population_within_100_km=population_within_100_km/1e6)

ggplot() + 
coord_sf()+ 
  geom_sf(data = dVolcano,
                    aes(fill = population_within_100_km))+theme_void()+
  labs(title="Population at risk during volcanic eruptions",
       subtitle="Population within 100 km of volcanic eruption",
       caption = "Source: Volcanic eruptions")  +
  scale_fill_continuous(name =  "Population in millions")

volcanic_eruptions<-volcano  %>%
  left_join(eruptions, by="volcano_number")%>% 
  filter(start_year>=2000) %>% 
  mutate(population_within_100_km=population_within_100_km/1e6)

dEruptions_2000 <-world  %>%
  left_join(volcanic_eruptions, c("name_sort"="country")) %>% 
  rename(country=name_sort) 

ggplot() + 
coord_sf()+ 
  geom_sf(data = dEruptions_2000,
                    aes(fill = population_within_100_km))+theme_void()+
  labs(title="Volcanic eruptions since year 2020",
       subtitle="Population within 100 km of volcanic eruption",
       caption = "Source: Volcanic eruptions") +
  scale_fill_continuous(name =  "Population in millions")


events_factored<- 
  events %>% select(event_type) %>% 
  filter(!is.na(event_type)) %>% 
  mutate(event_type = fct_lump(event_type, n = 10,other_level = "Other")) %>%          count(event_type) 

events_factored %>% 
  ggplot(mapping = aes(x=n,y=fct_reorder(event_type,.x = n))) +
  geom_col() +
  labs(title = "Frequency of causes for volcanic events", 
       caption="Economist theme",
       x="Frequency of volcanic events",
       y="Cause of volcanic events")+
  ggthemes::theme_economist( base_size = 12)+
  theme(axis.title.x = element_text(size = 12, face = "bold",
                                    margin = margin(t = 10, r = 00, b = 0, l = 0)))+
  theme(axis.title.y = element_text(size = 12, face = "bold",
                                    margin = margin(t = 0, r =10, b = 0, l = 00)))+
  theme(axis.title = element_text(margin = margin(t = 00, r = 0, b =00, l = 0))) + 
  theme(plot.title = element_text(size = 14, face = "bold",vjust = 3))


```

#Part4: How long have the volcanic eruptions continued ?

```{r}

volcano_duration<-eruptions %>% 
  select(volcano_name, eruption_number, start_year, end_year) %>% 
  drop_na() %>% 
  group_by(volcano_name) %>% 
  mutate(duration_year=end_year-start_year) %>% 
  filter(duration_year>0) %>% 
  arrange(desc(duration_year)) %>% 
  ungroup()



slice_head(volcano_duration,n=10) %>% 
  arrange(desc(duration_year)) %>% 
  kbl() %>%
  kable_styling()
  
```

#Part5: Has the same volcano eurpted again. If so, how many times ?

```{r}

volcano_eruption_frequency<-eruptions %>% 
  select(volcano_name, eruption_number) %>% 
  drop_na() %>% 
  group_by(volcano_name) %>% 
  count(volcano_name) %>% 
  ungroup()

volcano_eruption_frequency %>% 
  arrange(desc(n)) %>% 
  slice_max(n=20, order_by=n) %>% 
  kbl() %>%
  kable_styling()
  
```

#Part6: Plotting moving average for sulphur concentration in the atmosphere ?

```{r}

library(hrbrthemes)
library(extrafont)
library(ggpomological)
extrafont::font_import()

sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')

sulfur_mean_neem <-sulfur%>% 
  select(year, neem) %>% 
  mutate(mean_neem=mean(neem, na.rm=T),
         two_std=mean_neem+2*sd(neem,na.rm=T))

sulfur_mean_wdc <-sulfur%>% 
  summarize(mean_wdc=mean(wdc, na.rm=T))

plot_sulfur_neem <- sulfur %>%
  ggplot(aes(x = year, y = neem)) +
  geom_line(# plot raw values
    size = 1,
    alpha = 0.2) +
  tidyquant::geom_ma(# plot moving average
    n = 10,
    size = 1,
    color = "blue") +
  labs(
    title = "Sulfer detected from NEEM",
    subtitle = "Moving average in blue and 2 st dev in red ",
    caption =  "Data collected in ice cores from Greenland",
    x = "Year",
    y = "Sulfur concentration (ng/g) "
  ) +
  geom_line(data = sulfur_mean_neem, aes(x = year, y = two_std, color =
                                           "red"), linetype=2) +
  scale_fill_pomological() + theme_pomological_fancy()


plot_sulfur_wdc <- sulfur %>%
  ggplot(aes(x = year, y = wdc)) +   # start ggplot
  geom_line(# plot raw values
    size = 1,
    alpha = 0.2) +                      # semi-transparent line)
  tidyquant::geom_ma(# plot moving average
    n = 10,
    size = 1,
    color = "blue") +
  labs(
    title = "Sulfer detected from WDC",
    subtitle = "Moving average across one year shown in blue",
    caption =  "Data collected in ice cores from Antartica",
    x = "Year",
    y = "Sulfur concentration (ng/g) "
  ) +
  scale_fill_pomological()+theme_pomological_fancy()
 

plot_sulfur_neem
```
#Part7: Reproducing the tidyTuesday plot

```{r}

library(readxl)
VEI <- read_excel("data/VEI.xlsx") %>% 
  clean_names() %>% 
  drop_na %>% 
  mutate(vei_scaled=if_else(vei<5,vei/1e9, vei)) %>% 
  mutate(vei_scale=10**(vei))


VEI %>% 
  ggplot(date=VEI) +
  geom_point(aes(x=1, y=vei,size=vei, 
                 colour= brewer.pal(n = 9, name = "BuGn")))+ scale_y_log10()+ 
  theme(legend.position = "none") 
  
```
