---
title: 'Project2: Network data'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

#Part1: Getting the data

```{r}

library(readr)
library(tidyverse)
library(dplyr)
library(readtext)
library(tidygraph)
library(ggraph)
library(igraph)

movies<-readtext("Movies.paj")
movies$text
start_nodes<-str_locate(movies$text,"\\*Vertices")
start_edge<-str_locate(movies$text,"\\*Edges")
end_nodes<-str_locate(movies$text,"\\*Arcs")
end_edge<-str_locate(movies$text,"\\*Partition")

nodes_data<-movies$text %>%
  str_sub(start=start_nodes[1], end = end_nodes[1]-1) %>%
  read_table( skip=1, col_names = F) %>% 
  map_df(str_trim) %>% 
  mutate(X2=str_extract(X2,"\\w+" ),
         X7=str_extract(X3,"[A-Z]++[\\. ]" ),
         full_name=str_c(X7, X2, sep=" "))
  

edges_data<-movies$text %>%
  str_sub(start=start_edge[1], end = end_edge[1]-1) %>%
  read_table( skip=1, col_names = F) %>% 
  rename(from=X1, to=X2)

movies_network<-tbl_graph(nodes=nodes_data, 
                          edges = edges_data,
                          directed = TRUE)

movies_network

library(ggraph)

movies_network %>% 
  ggraph() + 
  geom_edge_link(colour = 'grey') + 
  geom_node_point(size = 2) +
  theme_graph()


```

#Part2: Initial visualizations

```{r}

from_vect<-movies_network%>% 
  activate(edges) %>% 
  pull(from) %>% 
  unique()
  
movies_network<-movies_network %>% 
  activate(nodes) %>% 
  mutate(role=if_else(X1 %in% from_vect, "producer", "composer"))

movies_network %>% 
  ggraph() + 
  geom_edge_link(colour = 'grey') + 
  geom_node_point(aes(colour=role),size = 2) +
  geom_node_text(aes(label = full_name), repel=TRUE)+theme_graph()


producers_edges <- edges_data %>%    #edges tibble
  group_by(to) %>%    # grouping by composers
  mutate(new_from = list(unique(from))) %>%   # cumulate all the unique froms this to is connected to 
  unnest_longer(new_from) %>%    
  filter(from != new_from) %>%    
  ungroup() %>%    
  select(to = from, from = new_from)
#aes(color=role)

  
producers_edges  %>% 
  ggraph() + 
  geom_edge_link(colour = 'grey') + 
  geom_node_point(aes(colour='to')) +
  geom_node_text( repel=TRUE)+theme_graph()


```
  
```

movie <- as_tbl_graph(movie_network, directed = TRUE)
movie

movie %>% 
  ggraph() + 
  geom_edge_link(colour = 'grey') + 
  geom_node_point(size = 5) +
  theme_graph()


# grouping in some categories

movie <-
  movie %>%
  activate(nodes) %>% 
  mutate(group = group_leading_eigen())


movie %>% 
  mutate(group = as.factor(group)) %>% 
  ggraph() + 
  geom_edge_link(colour = "grey") + 
  geom_node_point(aes(colour = group), size = 5) +
  theme_graph()
